# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install python version 2 on ubuntu
  hosts: ubuntu
  gather_facts: no
  tasks:
  - name: Install python version 2 on ubuntu
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

#- name: Playbook for preparations
#  hosts: all
#
#  roles:
#  - role: osism.docker

- name: Playbook for role testing
  hosts: all

  roles:
  - role: ansible-hosts
