---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: $PLATFORM_NAME
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
scenario:
  name: default
