---
- name: Playbook for preparations
  hosts: all

  tasks:
  - name: Create /etc/hosts.molecule file
    file:
      path: /etc/hosts.molecule
      state: touch
      owner: root
      group: root
      mode: 0644
    become: true

- name: Playbook for role testing
  hosts: all

  vars:
    hosts_file: /etc/hosts.molecule

  roles:
    - role: ansible-hosts
