#!/usr/bin/env bash

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# Available environment variables
#
# OPENRCFILE

# Set default values

OPENRCFILE=${OPENRCFILE:-openrc}
if [[ -e $OPENRCFILE ]]; then
    source $OPENRCFILE
fi

if [[ -e tox.ini ]]; then
    tox -e destroy
fi
